<?php
/**
 * Created by PhpStorm.
 * User: ljy
 * Date: 17/9/26
 * Time: 下午2:14
 */

namespace app\television\controller;

use think\Db;
use think\Request;
use think\session;
class Index extends Base
{
    public $cash_money ='';
    public function _initialize()
    {
        $system = DB::name('system')->where(['id'=>1])->find();
        $this->cash_money = $system['convert_scale4']/$system['convert_scale3'];
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    public function index(){
        $member =session::get("member");
        $tv_id = $member["member_id"];
        $system = DB::name("system")->where(["id"=>1])->find();
        //获取主播数量
        $anchor_map["a.type"] = 3;
        $anchor_map["is_del"] =1;
        $anchor_map["b.tv_id"] = session('member')["member_id"];
        $anchor_count = DB::name("Member")->alias("a")->join("th_anchor_info b","a.member_id=b.anchor_id")->where($anchor_map)->count();
        //主播收益(总收益额)
        $anchor_id = DB::name("Member")->alias("a")->join("th_anchor_info b","a.member_id=b.anchor_id")->where($anchor_map)->column("anchor_id");
        if(!empty($anchor_id)){
            $anchor_earnings = DB::name("Member")->where("member_id","in",$anchor_id)->sum("get_gift_count");
        }else{
            $anchor_earnings= 0;
        }
        //主播直播交易信息
        if(!empty($anchor_id)){
            $anchor_where["member_id"] = ['in',$anchor_id];
            $anchor_info = DB::name("Member")->field("username,phone,e_ticket,member_id,get_gift_count")->where($anchor_where)->order("intime desc")->select();
            foreach ($anchor_info as $k =>$v){
                //可提现金额
                $anchor_info[$k]["case_money"] = $v['e_ticket']*$this->cash_money;
            }
            $this->assign("anchor_info",$anchor_info);
        }else{
            $this->assign("anchor_info",[]);
        }
        $this->assign(['anchor_count'=>$anchor_count,'anchor_earnings'=>$anchor_earnings,'anchor_info'=>$anchor_info]);
        //获取商户数量
        $map['a.is_delete'] = 0;
        $map["b.type"] = 2;
        $map["a.tv_id"] = $tv_id;
        $map["a.platform_type"] =1;
        $merchants_count = DB::name("Merchants")
            ->alias('a')
            ->join('__MEMBER__ b','a.member_id = b.member_id')
            ->where($map)
            ->count();
        //商户总交易额
        $merchants_id =  DB::name("Merchants")
            ->alias('a')
            ->join('__MEMBER__ b','a.member_id = b.member_id')
            ->where($map)
            ->column("b.member_id");
        if(!empty($merchants_id)){
            $order["merchants_id"]  = ["in",$merchants_id];
            //商户直播收益
            $merchants_earninag = DB::name("Member")->where("member_id","in",$merchants_id)->sum("get_gift_count");
            //总销售额
            $merchants_sale = DB::name("order_settlement")->where(['merchant_id'=>['in',$merchants_id],'type'=>1])->sum("order_price");
            $merchants_where["a.member_id"] = ['in',$merchants_id];
            $merchants_info = DB::name("Merchants")
                ->alias("a")
                ->field("b.member_id,b.phone,b.e_ticket,b.get_gift_count,a.merchants_name,a.contact_name")
                ->join("__MEMBER__ b","a.member_id=b.member_id")
                ->where($map)
                ->order("a.create_time desc")
                ->select();
            //商户销售统计
            foreach ($merchants_info as $k=>$v){
                //直播可提现金额
                $merchants_info[$k]["case_money"] = $v['e_ticket']*$this->cash_money;
                //销售统计
                $merchants_info[$k]["order_price"] = DB::name('order_settlement')->where(['merchant_id'=>$v['member_id'],'type'=>1])->sum('order_price');
                $merchants_info[$k]["merchants_settlement_price"] = DB::name('order_settlement')->where(['merchant_id'=>$v['member_id'],'type'=>1])->sum('settlement_price');
                $merchants_info[$k]["anchor_settlement_price"] = DB::name('order_settlement')->where(['merchant_id'=>$v['member_id'],'type'=>2])->sum('settlement_price');
            }
        }else{
            $anchor_earnings =0;
            $merchants_earninag =0;
            $merchants_info =[];
            $merchants_sale=0;
        }
        $this->assign(['merchants_count' =>$merchants_count,'merchants_info'=>$merchants_info,'merchants_earninag'=>$merchants_earninag,'merchants_sale'=>$merchants_sale]);
        //电视台信息概况
        $tv_info = DB::name("Television")->where(["tv_id"=>$tv_id])->find();//直播收益
        $tv_info['cash_money'] = $tv_info['e_ticket']*$this->cash_money;
        $tv_info['settlement_count_price'] = DB::name('order_settlement')->where(['merchant_id'=>$tv_id,'type'=>3])->sum('settlement_price');
        //$tv_info['order_price_count'] = DB::name('order_settlement')->where(['merchant_id'=>$tv_id,'type'=>3])->sum('order_price');
        $this->assign(['tv_info'=>$tv_info]);
        return $this->fetch();
    }
}